# Generated by Django 3.2 on 2021-07-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20210511_1117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastrocliente',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='cadastrocliente',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='cadastrocliente',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='cadastrocliente',
            name='cpf',
        ),
        migrations.RemoveField(
            model_name='cadastrocliente',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cadastrocliente',
            name='logradouro',
        ),
        migrations.RemoveField(
            model_name='cadastrocliente',
            name='numero',
        ),
        migrations.RemoveField(
            model_name='cadastrocliente',
            name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='cadastrocliente',
            name='telefone',
        ),
        migrations.RemoveField(
            model_name='cadastrocliente',
            name='uf',
        ),
        migrations.AddField(
            model_name='cadastrocliente',
            name='estoque',
            field=models.IntegerField(default=0, verbose_name='Estoque'),
            preserve_default=False,
        ),
    ]
