# Generated by Django 3.2 on 2021-07-10 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210709_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrocliente',
            name='fornecedor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='crud.fornecedores'),
        ),
        migrations.AlterField(
            model_name='fornecedores',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome fornecedor'),
        ),
    ]
