# Generated by Django 3.2 on 2021-07-10 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20210709_2221'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CadastroCliente',
            new_name='CadastroProdutos',
        ),
    ]
