# Generated by Django 3.2 on 2021-07-10 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0006_rename_cadastrocliente_cadastroprodutos'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastroprodutos',
            name='valor_de_venda',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Preço de Venda'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='VendaProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criacao', models.DateField(auto_now_add=True, verbose_name='Criado')),
                ('alteracao', models.DateTimeField(auto_now=True, verbose_name='Alterado')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Quantidade')),
                ('produto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crud.cadastroprodutos')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
